Traceback (most recent call last):
  File "/home/users/mhturner/SC-FC/voxel_subsample_analysis.py", line 33, in <module>
    roi_mask, roi_size = RegionConnectivity.loadAtlasData()
  File "/home/users/mhturner/SC-FC/region_connectivity/RegionConnectivity.py", line 61, in loadAtlasData
    roi_names = pd.read_csv(os.path.join(data_dir, fn_names), sep=',', header=0).name.to_numpy()
  File "/home/groups/trc/python/lib/python3.6/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/groups/trc/python/lib/python3.6/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/groups/trc/python/lib/python3.6/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/home/groups/trc/python/lib/python3.6/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/groups/trc/python/lib/python3.6/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 374, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 673, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File /home/mhturner/Dropbox/ClandininLab/Analysis/hemibrain_analysis/roi_connectivity/data/Original_Index_panda_full.csv does not exist: '/home/mhturner/Dropbox/ClandininLab/Analysis/hemibrain_analysis/roi_connectivity/data/Original_Index_panda_full.csv'
